name: Continuous integration

on:
  push:
    branches-ignore:
      - 'master'

jobs:
  build:
    # ==================================================================================================================
    # Configuration.
    runs-on: ubuntu-latest

    steps:
      # ================================================================================================================
      - name: GPG Setup
        id: gpg
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
        run: |
          echo "$GPG_PRIVATE_KEY" > private.asc
          gpg --import --batch private.asc

      # ================================================================================================================
      - name: JDK 11 Setup
        id: jdk
        uses: actions/setup-java@v1
        with:
          java-version: 11.0.x
          server-id: ossrh
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD

      # ================================================================================================================
      - name: Retrieve the sources
        id: sources
        uses: actions/checkout@v1

      # ================================================================================================================
      - name: Retrieve the version
        id: version
        run: |
          echo "::set-output name=version::$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)"

      # ================================================================================================================
      - name: Install vuepress and build the documentation web site
        run: |
          yarn global add vuepress
          yarn --cwd docs build

      # ================================================================================================================
      - name: Deploy the documentation web site
        uses: JamesIves/github-pages-deploy-action@4.1.0
        with:
          branch: gh-pages
          folder: docs/src/.vuepress/dist
          commit-message: "Documentation web site update for ${{ steps.version.outputs.version }}"
          clean: true

      # ================================================================================================================
      - name: Creates a Qase run
        id: qase
        run: |
          echo "::set-output name=qase_run_id::$( \
            curl -s "https://api.qase.io/v1/run/CTB" \
            -X POST \
            -H "Token: ${{ secrets.QASE_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d '{"title": "${{ github.event.head_commit.message }}","description": "Test run for ${{ steps.version.outputs.version }}","environment_id": null,"cases": []}' \
            | jq -r -c ".result.id")"

      # ================================================================================================================
      - name: Build, run tests, package and deploy to Maven central - Also sends Qase tests reports
        id: package
        env: # Environment variables.
          # GPG.
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
          # OSSRH credentials.
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
        run: |
          mvn deploy -B -Dgpg.passphrase=${GPG_PASSPHRASE} \
            -Dqase.enable=true \
            -Dqase.project.code=CTB \
            -Dqase.run.id=${{ steps.qase.outputs.qase_run_id }} \
            -Dqase.api.token=${{ secrets.QASE_TOKEN }}

      # ================================================================================================================
      - name: Test Cassandre trading bot maven archetype - basic strategy
        id: cassandre-trading-bot-spring-boot-starter-basic-archetype
        run: |
          mvn -B archetype:generate \
            -DarchetypeGroupId=tech.cassandre.trading.bot \
            -DarchetypeArtifactId=cassandre-trading-bot-spring-boot-starter-basic-archetype \
            -DarchetypeVersion=${{ steps.version.outputs.version }} \
            -DgroupId=com.example \
            -DartifactId=archetype-test-basic \
            -Dversion=1.0-SNAPSHOT \
            -Dpackage=com.example
          mvn -f archetype-test-basic/pom.xml compile

      # ================================================================================================================
      - name: Test Cassandre trading bot maven archetype - basic ta4j strategy
        id: cassandre-trading-bot-spring-boot-starter-basic-ta4j-archetype
        run: |
          mvn -B archetype:generate \
            -DarchetypeGroupId=tech.cassandre.trading.bot \
            -DarchetypeArtifactId=cassandre-trading-bot-spring-boot-starter-basic-ta4j-archetype \
            -DarchetypeVersion=${{ steps.version.outputs.version }} \
            -DgroupId=com.example \
            -DartifactId=archetype-test-ta4j-basic \
            -Dversion=1.0-SNAPSHOT \
            -Dpackage=com.example
          mvn -f archetype-test-ta4j-basic/pom.xml compile
