name: Integration tests

on:
  schedule:
    - cron: '0 2 1 * *'

jobs:
  build:
    # ==================================================================================================================
    # Configuration.
    runs-on: ubuntu-latest

    steps:
      # ================================================================================================================
      - name: Retrieve the sources
        uses: actions/checkout@v1

      # ================================================================================================================
      - name: JDK 11 Setup
        uses: actions/setup-java@v1
        with:
          java-version: 11.0.x

      # ================================================================================================================
      - name: Build, run tests, package and deploy to Maven central
        env: # Environment variables.
          # Kucoin credentials.
          KUCOIN_NAME: ${{ secrets.KUCOIN_NAME }}
          KUCOIN_USERNAME: ${{ secrets.KUCOIN_USERNAME }}
          KUCOIN_PASSPHRASE: ${{ secrets.KUCOIN_PASSPHRASE }}
          KUCOIN_KEY: ${{ secrets.KUCOIN_KEY }}
          KUCOIN_SECRET: ${{ secrets.KUCOIN_SECRET }}
        run: |
          mvn -Pintegration package
