name: Integration tests

on:
  schedule:
    - cron: '0 18 * * SUN'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # ================================================================================================================
      - name: JDK 11 Setup
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      # ================================================================================================================
      - name: Retrieve the sources
        uses: actions/checkout@v2

      # ================================================================================================================
      - name: Retrieve the sources
        uses: actions/checkout@v2
        with:
          repository: straumat/XChange
          path: xchange

      # ================================================================================================================
      # TODO, remove personnal xchange build
      - name: Build and run integration tests
        env:
          # Kucoin credentials.
          KUCOIN_NAME: ${{ secrets.KUCOIN_NAME }}
          KUCOIN_USERNAME: ${{ secrets.KUCOIN_USERNAME }}
          KUCOIN_PASSPHRASE: ${{ secrets.KUCOIN_PASSPHRASE }}
          KUCOIN_KEY: ${{ secrets.KUCOIN_KEY }}
          KUCOIN_SECRET: ${{ secrets.KUCOIN_SECRET }}
          # Gemini credentials.
          GEMINI_NAME: ${{ secrets.GEMINI_NAME }}
          GEMINI_USERNAME: ${{ secrets.GEMINI_USERNAME }}
          GEMINI_PASSPHRASE: ${{ secrets.GEMINI_PASSPHRASE }}
          GEMINI_KEY: ${{ secrets.GEMINI_KEY }}
          GEMINI_SECRET: ${{ secrets.GEMINI_SECRET }}
          # Coinbase pro credentials.
          COINBASE_PRO_NAME: ${{ secrets.COINBASE_PRO_NAME }}
          COINBASE_PRO_USERNAME: ${{ secrets.COINBASE_PRO_USERNAME }}
          COINBASE_PRO_PASSPHRASE: ${{ secrets.COINBASE_PRO_PASSPHRASE }}
          COINBASE_PRO_KEY: ${{ secrets.COINBASE_PRO_KEY }}
          COINBASE_PRO_SECRET: ${{ secrets.COINBASE_PRO_SECRET }}
          # Binance credentials.
          BINANCE_NAME: ${{ secrets.BINANCE_NAME }}
          BINANCE_USERNAME: ${{ secrets.BINANCE_USERNAME }}
          BINANCE_PASSPHRASE: ${{ secrets.BINANCE_PASSPHRASE }}
          BINANCE_KEY: ${{ secrets.BINANCE_KEY }}
          BINANCE_SECRET: ${{ secrets.BINANCE_SECRET }}
        run: |
          mvn -f xchange/xchange-kucoin/pom.xml install -Dgpg.skip -Dmaven.test.skip=true
          mvn -f xchange/xchange-gemini/pom.xml install -Dgpg.skip -Dmaven.test.skip=true
          mvn test -Pintegration
