name: Website update

on:
  push:
    branches:
      - "development"

jobs:
  build:
    # ==================================================================================================================
    # Configuration.
    runs-on: ubuntu-latest

    steps:
      # ================================================================================================================
      - name: Retrieve the sources
        id: sources
        uses: actions/checkout@v1

      # ================================================================================================================
      - name: Install vuepress and build the documentation website
        run: |
          yarn global add vuepress
          yarn global add @vuepress/plugin-google-analytics
          yarn global add @vuepress/plugin-medium-zoom
          yarn global add @vuepress/plugin-back-to-top
          yarn --cwd docs build docs --debug

      # ================================================================================================================
      - name: Deploy the documentation website
        uses: JamesIves/github-pages-deploy-action@4.1.0
        with:
          branch: gh-pages
          folder: docs/src/.vuepress/dist
          commit-message: "Documentation website update"
          clean: true
